name: webssh

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '12 12 * * *'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rcdfrd/webssh
          tags: |
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Asia/Shanghai'}}
            type=raw,value=latest
      - 
        name: Clone source code
        run: |
          git clone https://github.com/huashengdun/webssh.git webssh
      -
        name: Check
        run: |
          if [ $(( $( date '+%s' ) - $( date -d $(curl -k https://api.github.com/repos/openfaas/faas | jq --raw-output '.updated_at') '+%s' ) )) -lt 172800 ]; then build=true; fi
          echo $build
      -
        name: Build and push
        if: env.build == true
        uses: docker/build-push-action@v3
        with:
          context: webssh
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
